---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint .
platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRIBUTION:-ubuntu2004}-ansible:latest"
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    exposed_ports:
      - 80/tcp
    published_ports:
      - 0.0.0.0:80:80/tcp
provisioner:
  name: ansible
